### ISSUE TITLE
How to inspect the element by using the JavaScript

### ISSUE THREAD

**Issue by smallisettyzc** [barmalei/zebkit#4]
As part of our automation testing, we want to inspect the elements.

Is it possible to inspect the element or is there any way to parse the canvas to HTML along with the javascript events.

**Comment by barmalei** [comment]
What are "the elements" in a context of zebkit ?

**Comment by smallisettyzc** [comment]
I mean we want to inspect the HTML controls inside of canvas.

**Comment by barmalei** [comment]
If you insert HTML elements inside zebkit canvas that means they are wrapped as zebkit UI components.  Taking this in account you can find them as any other zebkit UI component with "find(...)" or "findAll(...)" method. For instance imagine you need to get all UI components that are instance of "zebkit.ui.web.HtmlElement" class:
```js
var z = new zCanvas(...);
...
// find recursively all UI components that are instance of  zebkit.ui.web.HtmlElement class
z.root.findAll("~zebkit.ui.web.HtmlElement", function(component) {
      component.element; // access DOM element that is wrapped with zebkit UI component 
});
```

Pay attention, that real DOM element is accessible as "element" field of appropriate zebkit UI component.

**Comment by smallisettyzc** [comment]
Hi @barmalei ,
Thanks for your reply.

I am able to get all the elements based on type by using 
`zebra.ui.$detectZCanvas('$zObj_435').findAll('zebra.ui.TextField')` .

I don't have any id for individual control. Is it possible to find using the **$hash$**?

I am trying by using this.
https://github.com/barmalei/zebkit/blob/master/src/js/layout.js#L322

**Comment by smallisettyzc** [comment]
Just to update, it making use of zebra repo instead of Zebkit.

We have tried few approaches to check is there any possibility as per specified in 
https://github.com/barmalei/zebra/blob/master/src/util.js#L199 .

We found that regex is not allowing $ in attribute name.
https://github.com/barmalei/zebra/blob/master/src/util.js#L220

Can you suggest is there any other approach.

**Comment by barmalei** [comment]
Actually zebkit is near future of zebra project, zebra is frozen and have not got updates for a long period of time.

**Comment by smallisettyzc** [comment]
thanks @barmalei .
I am able to access the elements. You really helped me.
